### ISSUE TITLE
 Direct script access is denied

### ISSUE THREAD

**Issue by jowodo** [nd1012/MarkDown-Server#3]
Dear nd, 

On ubuntu 16.04, apache 2.4.18, php 7.0.33
I cloned the repo into my home and copied what I needed into a subdirectory of /var/www/html/ `/var/www/html/pur/test/`, i.e. `.htaccess`, `mdserver.php`, `mdserver.conf.php` and of course a `index.md` from the demo directory. 
I tried to put these files into `/var/www/html/` but without any results. 
In the browser when I go to mydomain.com/pur/test is just get the content of the directory. 
I verified that the rewrite module is enabled with `a2query -m | grep rewrite` 
In the `.htaccess`  file I changed `/mdwebroot/` to `/var/www/html/pur/test/` and the last line to `RewriteRule ^(.*)$ /var/www/html/pur/test/mdserver.php $1 [NC,L]` which I don´t understand ... 
I tried in `/var/www/html/pur/test/` to execute `php mdserver.php [index.md]` and got the following error: 
`PHP Warning:  Direct script access is denied in /var/www/html/john/test/mdserver.php on line 248` 

This is my `mdserver.conf.php`: 
```
<?php

// Server-side cache
define('CACHE_ENABLED',true);// If the server cache is enabled
//define('HTML_CACHE_DIR','//to/mdwebroot');// Path to the HTML cache folder (without trailing slash, set to NULL, if cache is disabled and the HTML generator command won't write a file)
define('HTML_CACHE_DIR','/var/www/html/pur/test');// Path to the HTML cache folder (without trailing slash, set to NULL, if cache is disabled and
the HTML generator command won't write a file)
define('MKDIR_MODE',0775);// Access mode for created folders in the HTML cache folder
define('DISABLE_HOOK',false);// Disable PHP hook?

// APCu for the server-side cache
define('USE_APCU',true);// Use APCu for in-memory-caching, if available (won't write cached HTML into the HTML cache folder then)
define('APCU_TTL',60*60*24*30);// APCu cache TTL in seconds (should be greater than zero - however, zero would disable TTL)

// Client-side cache
define('MAX_CACHE_TIME',60*60*24*30);// Maximum cache time in seconds (zero to disable client cache support)

// MarkDown rendering
//define('MD_TO_HTML_CMD','/usr/bin/markdown -f +fencedcode,-style {mdfile} > {htmlfile}');// Command to transform MarkDown to HTML ("{mdfile}" is the MarkDown file path, "{htmlfile}" the HTML file path, paths will be shell argument escaped)
define('MD_TO_HTML_CMD','/usr/bin/markdown {mdfile} > {htmlfile}');// Command to transform MarkDown to HTML ("{mdfile}" is the MarkDown file path, "{htmlfile}" the HTML file path, paths will be shell argument escaped)
//define('MD_TO_HTML_CMD','/usr/bin/redcarpet --parse-fenced-code-blocks --render-with-toc-data {mdfile} > {htmlfile}');// Command to transform MarkDown to HTML ("{mdfile}" is the MarkDown file path, "{htmlfile}" the HTML file path, paths will be shell argument escaped)
define('DISABLE_HEADER_FOOTER',false);// Disable custom header/footer?

// Help for the MarkDown command can be found here: https://manpages.debian.org/bullseye/discount/markdown.1.en.html
// Help for the redcarpet command can be found here: https://github.com/vmg/redcarpet

// Contributed APCu cache tools
define('APCU_SECRET','');// Leave empty to disable authentication
``` 

Do you have any idea what I could be doing wrong? 
Thanks in advance

**Comment by nd1012** [comment]
Hi,

in the `.htaccess` file the line `RewriteBase /mdwebroot/` needs to contain the webroot relative to your domain. For example, if your domain is `yourdomain.com`, and the `test` folder (which contains the `mdserver.php`) can be accessed with `https://yourdomain.com/test/`, the line should be `RewriteBase /test/`.

The last line `RewriteRule ^(.*)$ /path/to/mdwebroot/mdserver.php/$1/ [NC,L]` targets the `mdserver.php` as request handler and provides the called URI as path information to the PHP script, which is available in the `$_SERVER['PATH_INFO']` environment variable. Here you have to change the absolute path to the `mdserver.php`, in your case it should be `RewriteRule ^(.*)$ /var/www/html/pur/test/mdserver.php/$1/ [NC,L]`.

In the `mdserver.conf.php` you configured the `HTML_CACHE_DIR` to be `/var/www/html/pur/test/`, which is fine, if the Apache user context (which should be `www-data`) has write permissions to that folder - but since your configuration uses APCu, if available, no files will be written to that folder anyway. So `www-data` isn't required to have write permissions (which is the very best case!).

An existing MarkDown converter (as configured in `MD_TO_HTML_CMD`) is required - I assume you setup it already.

Finally I assume, if you modify the `.htaccess` file as described, there's an `index.md` in the folder, and everything else is setup properly (APCu etc.), you should be able to point your browser to `https://yourdomain.com/test/` and see the resulting HTML.

The `mdserver.php` isn't designed to be called directly or as CLI script from the shell. It'll only work when being called by the `.htaccess` rewrite rules during handling a http request.

Ok, now I hope it's working for you!
